#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "install included packages"
priority = -11

dependencies = [
    "core/pkg-update",
]
