#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "thin-edge.io default recipes"
dependencies = [
    "core/persist-root-home",

    "essentials",
    "persist-network-manager",
    # "set-wifi",
    "ssh",

    # containers
    # "docker",

    # default cmdline options
    "boot-options",

    # enable mdns (for statically compiled musl binaries)
    # "systemd-resolved",
]