#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "tedge-alpine-320-efi"

recipes = [
    # Remove apk packages that have GPL-v3 license 
    "remove-gpl3",

    # Install included apk packages
    "install-included",

    # Optional: can add user and set password for root user
    # "add-user"

    # Install Podman
    "podman-alpine"
]