#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "core/alpine-3-20"

# Need recipes for Alpine 
recipes = [
    # default tedge packages -- for Alpine
    "defaults",

    # Setup the network -- for Alpine
    "setup-network", 
    # Current one has apt-get and systemctl

    # PKCS11 tools -- its dependency thin-edge.io(recipes) needs to be modifies for Alpine (apk)
    "setup-pkcs11",

]