#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-layer.schema.json
parent = "tedge-alpine-320"

recipes = [
    # Setup Debian for booting via Grub.
    "core/alpine-grub-setup"
]