#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "install podman for alpine"
dependencies = [
    "tedge-community-repo",
    "thin-edge.io",
]
