#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "thin-edge.io default recipes"
dependencies = [
    "core/persist-root-home",

    "essentials-alpine",
    "persist-network-manager",
    "ssh",

    # default cmdline options
    "boot-options",

]