#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-recipe.schema.json
description = "thin-edge.io essential recipes"
dependencies = [
    "thin-edge.io",
    "persist-data",
    "persist-overlay",
    "tedge-bootstrap",
    "tedge-local-pki",
    "tedge-firmware-update",
    "mosquitto",
]