listener 1884 10.89.0.1
# Alternative is to create a tedge-network alias in /etc/hosts:
#   10.89.0.1       tedge-network
# And then reference the alias in the mosquitto listener:
#   listener 1884 tedge-network
allow_anonymous true
require_certificate false
